### ISSUE TITLE
Feature extraction for CORNet-S

### ISSUE THREAD

**Issue by antoniyaaboyanova** [ViCCo-Group/thingsvision#128] opened 2023-02-01 18:39 UTC
Hi guys, 

I am using your library to extract features from different models including the cornet family. With all of the models my results make sense (RSA with human data) except for CORNet-S. I did a test where I use the model pre-trained vs not and couldn't see a systematic difference in the outcome. It's strange because everything seems to work perfectly well for the features extracted from the other models (i.e. other two cornets, vgg16, alexnet, resnet50).  So I wanted to ask if anyone else has had some issues with the CORNet-S features and if you have any suggestions on what could be the problem?

**Comment by Alxmrphi** [comment] 2023-02-01 18:44
I'm sorry, I didn't understand what problem you were referring to. What's the issue? Being specific is great, as it allows us to check the code and run tests and hopefully identify a problem.

- Alex

**Comment by antoniyaaboyanova** [comment] 2023-02-01 19:06
Hi,

Thank you for your reply. I think that CORNet-S might not have the right
pretrained weights when I am calling the model. The reason why I am
thinking this might be so is that the RSA analysis I am doing with the
features extracted from this model just don't make sense, but the results
for all of the other models are aligned to their behavioural performance.
Additionally I apply SVM on the extracted features and as I go deeper in
layers the SVM's performance gets better - that's the case with all other
models I've used, except for CORnet-S. So I am trying to figure out why
this is so. Moreover, when I look at the final performance of the models on
the images I have, CORnet-S is one of the best performing models, so I am
super confused as to why when I try to do decoding based on its features
the performance is so poor.

Please don't hesitate to ask me further questions if something is unclear.

Any insight on the matter would be greatly appreciated. Also potential
suggestions on what I can do differently would be helpful as well. I want
to use your library for all feature extraction as it keeps it very
consistent.

Best,
Antoniya

**Comment by andropar** [comment] 2023-02-06 14:47
Hi Antoniya,

I checked our code for the different CORnet versions, and all models, including CORnet-s, correctly pull pretrained state dicts from the official AWS bucket and load their weights from them. This is more or less identical to the [official CORnet repository](https://github.com/dicarlolab/CORnet). Model outputs also differ between pretrained and random weight initialization and resulting RDMs for some images I had lying around look significantly different. 

For me, this suggests that on our side things should work as intended. Could you maybe post the code you used to do your feature extraction and analyses? Also, what version of `thingsvision` do you use?

Best,
Johannes

**Comment by LukasMut** [comment] 2023-02-06 17:47
Could this be for some reason related to #46?

**Comment by antoniyaaboyanova** [comment] 2023-02-07 18:02
Hi,

Thanks for your reply and help! Attached you will find my code for the
extraction + SVM. The thingsvision I am using is: 2.2.18. I do apply PCA to
the features once I extract them for storage purposes - could this be
causing a weird effect on the features?

Best,
Antoniya

**Comment by andropar** [comment] 2023-02-09 12:22
@antoniyaaboyanova, you'll have to post the code into the Github issue, I don't think you can attach files when answering by mail! 🙂

**Comment by LukasMut** [comment] 2023-03-06 12:29
I think this is not an issue on our end. @andropar, can we close this?

**Comment by andropar** [comment] 2023-03-06 12:39
Yes, I think so too.

**Closed** 2023-03-06 12:43 UTC
